const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PROFESIONAL: 'PROFESIONAL',
};

const ESTADOS_TURNO = {
  PENDIENTE: 'PENDIENTE',
  CONFIRMADO: 'CONFIRMADO',
  CANCELADO: 'CANCELADO',
  COMPLETADO: 'COMPLETADO',
  AUSENTE: 'AUSENTE',
};

const ORIGEN_TURNO = {
  MANUAL: 'MANUAL',
  WEB: 'WEB',
};

module.exports = { ROLES, ESTADOS_TURNO, ORIGEN_TURNO };
